version: "3.3"

services:
  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock-supplier
    ports:
      - "8081:8080"
    volumes:
      - ./stubs:/home/wiremock
    command: [ "--global-response-templating", "--verbose" ]
    restart: unless-stopped
