spring:
  application:
    name: challenge
  datasource:
    url: jdbc:h2:file:./data/revenda_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    baseline-on-migrate: true
server:
  servlet:
    context-path: /api
feign:
  client:
    config:
      default:
        loggerLevel: full
resilience4j:
  retry:
    instances:
      fornecedorApiRetry:
        maxAttempts: 3
        waitDuration: 2000ms
        retryExceptions:
          - feign.FeignException$InternalServerError
          - feign.FeignException$ServiceUnavailable
app:
  fornecedor:
    url: ${SUPPLIER_URL:http://localhost:8081}
